name: roomloo
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.0

  # Firebase Authentication & Firestore
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.2.2

  # UI & Styling
  google_fonts: ^6.1.0
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.2  # For local storage
  flutter_svg: ^2.0.10  # For SVG icons
  connectivity_plus: ^6.0.3  # To check network status

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

 
  uses-material-design: true
